In [ ]:
import numpy as np
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.random.random((2,3))

array([[0.85982346, 0.42666089, 0.83315012],
       [0.61291411, 0.25326977, 0.85070126]])

In [ ]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c = np.array([[9,8,7], [1,2,2]])
d = np.array([[4,5,6], [9,8,9]])

c + d

array([[13, 13, 13],
       [10, 10, 11]])

In [ ]:
c * d

array([[36, 40, 42],
       [ 9, 16, 18]])

In [ ]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.55555556]])

In [ ]:
c ** 2

array([[81, 64, 49],
       [ 1,  4,  4]])

In [ ]:
a

array([6, 7, 8, 9])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c

array([[9, 8, 7],
       [1, 2, 2]])

In [ ]:
d

array([[4, 5, 6],
       [9, 8, 9]])

In [ ]:
a[0]

6

In [ ]:
a[3]

9

In [ ]:
b[1,2]

6

In [ ]:
b[0,0]

1

In [ ]:
c[0,1]

8

In [ ]:
d[1, 0:2]

array([9, 8])

In [ ]:

e = np.array([[10,11,12], [13,14,15], [16,17,18], [19,20,21]])

In [ ]:
sum(e)

array([58, 62, 66])

In [ ]:
e > e

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
import pandas as pd
days_list= pd.Series(["Monday", "Tuesdaay", "Wednesday"])
numpy_days = pd.Series(days_list)
print(numpy_days)

0       Monday
1     Tuesdaay
2    Wednesday
dtype: object


In [ ]:
days = pd.Series(["Monday", "Tuesdaay", "Wednesday"], index = ["a", "b","c"])
days

a       Monday
b     Tuesdaay
c    Wednesday
dtype: object

In [ ]:
days1 = pd.Series({"a": "Monday", "b": "Tuesday", "c": "Wednesday"})
days1

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [ ]:
days[0]

'Monday'

In [ ]:
days[1:]

b     Tuesdaay
c    Wednesday
dtype: object

In [ ]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [ ]:
df_dict = {"country": ["Ghana", "Kenya","Nigeria","Togo"],
           "capital": ["Accra", "Nairobi", "Abuja","Lome"],
           "population":[10000,8500,35000,12000],
           "age":[60,70,80,75]
           }
df = pd.DataFrame (df_dict, index = [2,4,6,8])
df

country  capital  population  age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [ ]:
df_list = [["Ghana", "Accra", 10000, 60],
           ["Kenya", "Nairobi", 8500, 70],
           ["Nigeria", "Abuja", 35000, 80],
           ["Togo", "Lome", 12000, 75]]
           
df1 = pd.DataFrame(df_list, columns = ["country", "capital", "population","age"],
                   index = [2,4,6,8]
                   )
df1

country  capital  population  age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [ ]:
df1.iloc[3]

country        Togo
capital        Lome
population    12000
age              75
Name: 8, dtype: object

In [ ]:
df1.loc[6]

country       Nigeria
capital         Abuja
population      35000
age                80
Name: 6, dtype: object

In [ ]:
df1.at[6, "country"]

'Nigeria'

In [ ]:
df1.iat[2,0]

'Nigeria'

In [ ]:
df1["capital"]

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: capital, dtype: object

In [ ]:
df1["population"].sum()

65500

In [ ]:
df1["population"].mean()

16375.0

In [ ]:
df1.mean()

population    16375.00
age              71.25
dtype: float64

In [ ]:
df.describe()

population        age
count      4.000000   4.000000
mean   16375.000000  71.250000
std    12499.166639   8.539126
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000

In [ ]:
df_dict2 = {"name": ["James", "Yemen","Caro", np.nan],
            "profession": ["Researcher", "Artist", "Doctor", "Writer"],
            "experience": [12, np.nan, 10, 8],
            "height": [np.nan, 175, 180, 150]
            }
new_df = pd.DataFrame(df_dict2)
new_df

name  profession  experience  height
0  James  Researcher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [ ]:
new_df.isnull()

name  profession  experience  height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [ ]:
new_df.dropna()

name profession  experience  height
2  Caro     Doctor        10.0   180.0

In [ ]:
pip install xlrd

In [122]:
fuel_data = pd.read_csv("fuel_data.csv")
fuel_data.to_csv("fuel_data.csv", index = False)
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [123]:
fuel_data.groupby("report_year")["report_year"].count()

report_year
1994    1235
1995    1201
1996    1088
1997    1094
1998    1107
1999    1050
2000    1373
2001    1356
2002    1205
2003    1211
2004    1192
2005    1269
2006    1243
2007    1264
2008    1228
2009    1222
2010    1261
2011    1240
2012    1243
2013    1199
2014    1171
2015    1093
2016    1034
2017     993
2018     951
Name: report_year, dtype: int64

In [124]:
fuel_data.groupby("fuel_type_code_pudl").first()

record_id  ...  fuel_cost_per_mmbtu
fuel_type_code_pudl                          ...                     
coal                  f1_fuel_1994_12_1_0_7  ...                1.121
gas                  f1_fuel_1994_12_2_0_10  ...                2.570
nuclear               f1_fuel_1994_12_2_1_1  ...                0.450
oil                   f1_fuel_1994_12_6_0_2  ...                5.469
other                f1_fuel_1994_12_11_0_6  ...                2.335
waste                 f1_fuel_1994_12_9_0_3  ...                1.072

[6 rows x 10 columns]

In [127]:
fuel_df1 = fuel_data.iloc[0:19000].reset_index(drop = True)
fuel_df2 = fuel_data.iloc[19000:].reset_index(drop = True)
assert len(fuel_data) == len(fuel_df1) + len(fuel_df2)

In [128]:
fuel_df2

record_id  ...  fuel_cost_per_mmbtu
0       f1_fuel_2009_12_79_0_2  ...               11.341
1       f1_fuel_2009_12_79_0_4  ...                1.108
2       f1_fuel_2009_12_79_0_5  ...                6.238
3       f1_fuel_2009_12_79_0_7  ...                4.885
4      f1_fuel_2009_12_79_0_10  ...                5.383
...                        ...  ...                  ...
10518  f1_fuel_2018_12_12_0_13  ...                9.030
10519   f1_fuel_2018_12_12_1_1  ...                6.950
10520  f1_fuel_2018_12_12_1_10  ...                8.990
10521  f1_fuel_2018_12_12_1_13  ...                1.110
10522  f1_fuel_2018_12_12_1_14  ...               11.680

[10523 rows x 11 columns]

In [136]:
fuel_data.mean()

utility_id_ferc1                1.186018e+02
report_year                     2.005806e+03
fuel_qty_burned                 2.622119e+06
fuel_mmbtu_per_unit             8.492111e+00
fuel_cost_per_unit_burned       2.086490e+02
fuel_cost_per_unit_delivered    9.175704e+02
fuel_cost_per_mmbtu             1.930435e+01
dtype: float64

In [138]:
fuel_data.groupby("fuel_type_code_pudl").sum()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
fuel_type_code_pudl                    ...                     
coal                           988354  ...          15275.11517
gas                           1425666  ...          62126.34574
nuclear                         87851  ...           1404.14500
oil                            913137  ...         102402.57762
other                           18448  ...          25899.18000
waste                           68026  ...         362815.08200

[6 rows x 7 columns]

In [141]:
fuel_data.skew()

utility_id_ferc1                  0.605070
report_year                       0.006953
fuel_qty_burned                  15.851495
fuel_mmbtu_per_unit               4.135217
fuel_cost_per_unit_burned        19.787440
fuel_cost_per_unit_delivered    105.014227
fuel_cost_per_mmbtu             171.675535
dtype: float64

In [142]:
fuel_data.kurt()

utility_id_ferc1                    1.088432
report_year                        -1.145656
fuel_qty_burned                   651.369450
fuel_mmbtu_per_unit                55.595695
fuel_cost_per_unit_burned         485.255851
fuel_cost_per_unit_delivered    11765.054226
fuel_cost_per_mmbtu             29489.132594
dtype: float64

In [144]:
fuel_data.mean()

utility_id_ferc1                1.186018e+02
report_year                     2.005806e+03
fuel_qty_burned                 2.622119e+06
fuel_mmbtu_per_unit             8.492111e+00
fuel_cost_per_unit_burned       2.086490e+02
fuel_cost_per_unit_delivered    9.175704e+02
fuel_cost_per_mmbtu             1.930435e+01
dtype: float64

In [147]:
fuel_data.groupby("report_year").mean()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
report_year                    ...                     
1994               106.120648  ...             3.086977
1995               110.139051  ...             2.868838
1996               108.714154  ...             2.695880
1997               108.366545  ...             3.113486
1998               109.845528  ...             2.775862
1999               108.222857  ...             2.740251
2000               111.083758  ...             4.208403
2001               113.521386  ...             4.612658
2002               120.354357  ...             6.226281
2003               123.300578  ...             7.223933
2004               121.123322  ...             8.441597
2005               121.028369  ...             9.397078
2006               117.178600  ...            10.339898
2007               116.040348  ...            10.735181
2008               120.785016  ...            12.690115
2009               118.139116  ...            10.619376
2010               117.992863  ...             8.551217
2011               121.069355  ...             9.237591
2012               120.769912  ...             8.808904
2013               122.082569  ...             9.308225
2014               129.263877  ...            10.064673
2015               128.591949  ...             8.054361
2016               133.117021  ...             6.915613
2017               131.126888  ...           368.736351
2018               133.669821  ...             7.233643

[25 rows x 6 columns]

In [149]:
len(fuel_data)

29523

In [150]:
180/29523

0.00609694136774718

In [151]:
0.00609694136774718 * 100

0.609694136774718

In [162]:

fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].sum()


fuel_type_code_pudl
coal        576254.381
gas         156891.829
nuclear    4053318.428
oil        1361824.819
other         3048.394
waste         8607.492
Name: fuel_cost_per_unit_burned, dtype: float64

In [165]:
fuel_data.corr()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
utility_id_ferc1                      1.000000  ...             0.006122
report_year                           0.093323  ...             0.010261
fuel_qty_burned                      -0.057447  ...            -0.001896
fuel_mmbtu_per_unit                  -0.066946  ...            -0.005884
fuel_cost_per_unit_burned            -0.037863  ...            -0.000437
fuel_cost_per_unit_delivered         -0.016414  ...            -0.000109
fuel_cost_per_mmbtu                   0.006122  ...             1.000000

[7 rows x 7 columns]

In [171]:
fuel_data.groupby(["report_year","fuel_type_code_pudl"]).aggregate({"fuel_cost_per_unit_burned": sum})

fuel_cost_per_unit_burned
report_year fuel_type_code_pudl                           
1994        coal                                 14984.572
            gas                                  10792.496
            nuclear                             227983.354
            oil                                   9362.194
            other                                  116.737
...                                                    ...
2018        coal                                  9488.197
            gas                                   4322.494
            nuclear                             173267.161
            oil                                  33836.602
            waste                                  660.972

[148 rows x 1 columns]

In [172]:
fuel_data.groupby(["report_year","fuel_type_code_pudl"]).aggregate({"fuel_cost_per_unit_burned": sum}).head(40)

fuel_cost_per_unit_burned
report_year fuel_type_code_pudl                           
1994        coal                                 14984.572
            gas                                  10792.496
            nuclear                             227983.354
            oil                                   9362.194
            other                                  116.737
            waste                                   52.762
1995        coal                                 14571.785
            gas                                   9087.905
            nuclear                             384152.639
            oil                                  17858.281
            other                                  183.577
            waste                                 -192.699
1996        coal                                 12694.803
            gas                                   1467.390
            nuclear                              66657.887
            oil                                   5357.028
            other                                  160.075
            waste                                   88.092
1997        coal                                 43742.178
            gas                                   1518.471
            nuclear                             112593.911
            oil                                   5387.536
            other                                  153.923
            waste                                  137.433
1998        coal                                 11902.597
            gas                                   7475.596
            nuclear                             117788.269
            oil                                   2608.657
            other                                  225.428
            waste                                  238.109
1999        coal                                 16303.468
            gas                                  16767.895
            nuclear                              62915.808
            oil                                  29654.510
            other                                  271.579
            waste                                  143.025
2000        coal                                100428.831
            gas                                  10024.878
            nuclear                             112375.382
            oil                                 104055.470

In [179]:

value_of_coal_1994 = 14984.572
value_of_coal_1998 = 11902.597

a = value_of_coal_1998 - value_of_coal_1994

In [180]:
a/value_of_coal_1994

-0.20567654518260517